### ISSUE TITLE
Upgrade Android SDK to v30

### ISSUE THREAD

**Issue by DesignrKnight** [dscnitrourkela/project-elaichi#108]
Reason for migration
- Android SDK 30 is lastest stable build for developers. Staying on the latest version comes with security and other new features.
- SDK 28(present SDK in code) is now deprecated by Google Play.

**Comment by abhibhaw** [comment]
Already Fixed

**Comment by Chinmay-KB** [comment]
If working, bump it to higher SDK ?

**Comment by abhibhaw** [comment]
31 needs a few package upgrades and configuration🤧
