### ISSUE TITLE
`Avenue` Application Setup

### ISSUE THREAD

**Issue by nayakastha** [dscnitrourkela/project-elaichi#146]
This issue belongs to:-
- [X] `elaichi`
- [ ] `dalchini`
- [ ] `project managment and overall`

**Describe the solution you'd like**

- [x] - Theme Setup - dark and light colours, fonts.
- [x] - Icons - adaptive icons, notification icons
- [ ] - Splash Screen 
- [x] - App Label change from `elaichi` to `Avenue`
- [x] - Release Config

**Comment by Chinmay-KB** [comment]
What's dalchini now 😱
