### ISSUE TITLE
Implement localization

### ISSUE THREAD

**Issue by Thesmader** [dscnitrourkela/project-elaichi#95]
### Context
Since we recently came around the problem with having string literals all over the codebase, we need to solve that problem.
### Requirements
1. We have the string literals defined in a single file in the form of key-value pairs and we access the values from that file wherever we need them in our codebase.
2. Static string literals can be directly accessed from the UI code where the ```context``` property is accessible. However, we also need to have a way to access them inside our view models without relying on the ```BuildContext```.
3. The syntax to use these values in code should be succinct and readable.
4. The solution should be compile-safe, i.e. if a value doesn't exist, the code should not compile.
### Possible Solutions
[Localization](https://flutter.dev/docs/development/accessibility-and-localization/internationalization) is the way to go. But the approach to localization presented in the Flutter Docs is a little heavy. The syntax is not very readable, involves boilerplate, and relies heavily on the ```context```. There are packages like [easy_localization](https://pub.dev/packages/easy_localization), [i18n](https://pub.dev/packages/i18n) and more. We need to choose a suitable package or come up with something to make the vanilla way fit our needs. @DesignrKnight @Chinmay-KB @ankank30 please take a look and suggest.

**Comment by DesignrKnight** [comment]
I like i18n. It is very easy to understand at least from the docs

**Comment by Thesmader** [comment]
I tried out easy_localization. I think it more or less fits our requirements. I am going ahead with it.
